base_config: configs/replica/replica.yaml

exp_name: replica/room0

data_specs:
  data_path: '../Datasets/Replica/room0'
  max_depth: 10
  use_gt: True

decoder_specs:
  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  # nice-slam's bound + [10,10,10]
  bound: [ [ 7.1,18.9 ],[ 6.8,15.5 ],[ 6.5,13.3 ] ]


