base_config: configs/scannet/scannet.yaml

exp_name: scannet/scene0050

data_specs:
  data_path: '../Datasets/scannet_data/scene0050_00'
  depth_scale: 1000.0
  crop: 6
  scale_factor: 0
  use_gt: True
  max_depth: 10

decoder_specs:
  bound: [ [ 8.0,18.0 ],[ 8.0,18.5 ],[ 8.0,16.5 ] ]
