base_config: configs/scannet/scannet.yaml

exp_name: scannet/scene0106

data_specs:
  data_path: '../Datasets/scannet_data/scene0106_00'
  depth_scale: 1000.0
  crop: 6
  scale_factor: 0
  use_gt: True
  max_depth: 5

decoder_specs:
  bound: [ [ 8.9,19.8 ],[ 9.0,20.0 ],[ 9.0,14.3 ] ] # nice-slam's bound + [10,10,10]